[package]
name = "terrain-gen-api"
version = "0.1.0"
edition = "2021"
description = "zero to production and midpnt displacement for terrain gen"
repository = "https://github.com/nuts-rice/terrain-gen-api"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.0"
log = { version = "0.4.17", features = ["std"] }
rapier3d = "0.17.1"

[dev-dependencies]
actix-rt = "2.8.0"
reqwest = "0.11.14"
tokio = "1.25.0"
